feat: Make the nested sections of the residence page folded by default.
enyosolutions-team/vue-awesome-components pull request #126
Opened 2021-01-08 11:10 UTC by Julien-Martin

> Trello card : https://trello.com/c/fXHw6bWS/888-make-the-nested-sections-of-the-residence-page-folded-by-default

2021-01-08 11:47 UTC, enyosolutions requested changes

2021-01-08 11:47 UTC, enyosolutions commented on src/components/crud/AwesomeCrud.vue
> -            :collapsible="false"
s'assurer que par l'action est bien a false dans le cas d'un awTable dans un awesomeCrud

2021-01-08 11:47 UTC, enyosolutions commented on src/components/crud/AwesomeForm.vue
> +                                    :data-toggle="ns.actions.collapsible ? 'collapse' : ''"
utiliser `_actions.collapsible`

2021-01-08 11:47 UTC, enyosolutions commented on src/components/crud/AwesomeForm.vue
> +                                  class="aw-crud-nested-model collapse"
Je pense qu'il faut aussi mettre le collapse uniquement si _actions.collapsible

2021-01-08 11:47 UTC, enyosolutions commented on src/components/table/AwesomeTable.vue
> +        v-if="_actions.collapsible"
rename collapsible => `collapse`  for consistency with the other actions

2021-01-08 11:47 UTC, enyosolutions commented on src/mixins/defaultProps.js
> +  collapsible: true,
rename to `collapse`

2021-01-08 11:47 UTC, enyosolutions commented on src/components/crud/AwesomeForm.vue
> +    this.nestedModels.forEach(nm => this.nestedModelsCollapseState[nm.identity] = nm.collapseInitialState)
`collapseInitialState` =>  `nestedModelIniallyCollapsed`  maybe ? (penser a mettre un `!`

2021-01-08 11:56 UTC, Julien-Martin commented on src/components/crud/AwesomeForm.vue
> +                                    :data-toggle="ns.actions.collapsible ? 'collapse' : ''"
@enyosolutions Justement ici on a besoin d'aller chercher l'actions du l'enfant, si on utilise `_actions.collapsible` on récupère celui du parent.

2021-01-08 12:04 UTC, Julien-Martin commented on src/components/crud/AwesomeForm.vue
> +    this.nestedModels.forEach(nm => this.nestedModelsCollapseState[nm.identity] = nm.collapseInitialState)
@enyosolutions J'ai renommé en `initiallyCollapsed` plus logique étant donnée que l'on est déjà dans l'object `nestedModel`
Pourquoi ajouté un `!` ?

2021-01-08 15:24 UTC, Julien-Martin commented
@enyosolutions Fixed

2021-01-11 09:18 UTC, enyosolutions commented
@Julien-Martin merge conflicts

2021-01-11 09:21 UTC, enyosolutions requested changes

2021-01-11 09:21 UTC, enyosolutions commented on src/components/crud/AwesomeForm.vue
> +    this.nestedModels.forEach(nm => this.nestedModelsCollapseState[nm.identity] = nm.initiallyCollapsed)
@Julien-Martin  il faut documenter cette prop quelque part sinon on va la perdre.

Soit dans les props de `AwesomeCrud`(meme si le composant ne l'utilisera pas)
Soit dans la documentation. Probablement commencer une documentation sur les nested models ?

2021-01-11 14:48 UTC, Julien-Martin commented on src/components/crud/AwesomeForm.vue
> +    this.nestedModels.forEach(nm => this.nestedModelsCollapseState[nm.identity] = nm.initiallyCollapsed)
@enyosolutions J'ai update la documentation en ajoutant `nestedModels` (juste la base, il y'a pas mal de chose à compléter dedans)

2021-01-13 10:43 UTC, enyosolutions commented
@Julien-Martin

2021-01-13 12:33 UTC, merged